---
title: "p8105_hw2_ncl2127"
author: "Nisha Lingam"
date: "2023-10-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```



Problem 2
```{r mr_trash_wheel creation, filtered irrelevant rows, updated homes_powered column}
mr_trash_wheel = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 1, cell_rows(c(2:549)))|>
  janitor::clean_names() |>
  mutate(homes_powered = (weight_tons*500)/30)

view(mr_trash_wheel)

```

```{r prof_trash_wheel creation, filtered irrelevant rows, updated homes_powered column}
prof_trash_wheel = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 2, cell_rows(c(2:108)))|>
  janitor::clean_names() |>
  mutate(homes_powered = (weight_tons*500)/30)

view(prof_trash_wheel)
```

```{r gwynnda_trash_wheel creation, filtered irrelevant rows, updated homes_powered column}
gwynnda_trash_wheel = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 4, cell_rows(c(2:157)))|>
  janitor::clean_names() |>
  mutate(homes_powered = (weight_tons*500)/30)

view(gwynnda_trash_wheel)
```

```{r}
##need to be aware of arguments into a function that predates tidyverse
```